### ISSUE TITLE
All tests are not loading 

### ISSUE THREAD

**Issue by resistancecanyon** [lloydwatkin/jquery.autocomplete#14]
The tests don't start to run at all and the test environment is failing.
Below is the error log.
> jquery.autocomplete@1.0.0 test /jquery.autocomplete
> mocha -R spec -t 60000 ./test/test
  HTML
    1) "before each" hook

  2) "after all" hook

  0 passing (2m)
  2 failing

  1)  "before each" hook:
     Error: timeout of 60000ms exceeded
      at null.<anonymous> (/jquery.autocomplete/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

  2)  "after all" hook:
     Error: timeout of 60000ms exceeded
      at null.<anonymous> (/query.autocomplete/node_modules/mocha/lib/runnable.js:158:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

npm ERR! Test failed.  See above for more details.

**Comment by destinmoulton** [comment]
I was able to run the tests fine. The command to run is 'npm test' from the parent dir.

**Comment by lloydwatkin** [comment]
Tests are running fine again in travis, you'll need to use nodejs 4.2 or run node with the `--harmony` flag in order to use the latest version of the selenium webdriver library.

**Comment by destinmoulton** [comment]
Nice!

**Comment by resistancecanyon** [comment]
@lloydwatkin 
I was using very old version of nodejs ~0.1.12
I updated to the latest version v5.0.0 & everything seems to run fine now.
All Tests(17) passing as of now.
Thanks for the reply.
Maybe add a node version dependency ?

**Comment by lloydwatkin** [comment]
Done in 86c876193883b550913abea3cd519de07900ceea

**Comment by resistancecanyon** [comment]
Cool 
Verified & Thanks
