### ISSUE TITLE
Persistent Npm Install Warnings

### ISSUE THREAD

**Issue by resistancecanyon** [lloydwatkin/jquery.autocomplete#21]
Do a fresh clone of repository
Run npm install
We get 2 persistent warnings.
npm WARN package.json jquery.autocomplete@1.0.0 No repository field.
npm WARN package.json jquery.autocomplete@1.0.0 No license field.

Please update repository & licence fields.

**Comment by lloydwatkin** [comment]
Feel free to add a pull request :) We're MIT here.

**Comment by resistancecanyon** [comment]
Added. Please review.
Also added a fix to #14 where the last commit breaks.

**Comment by lloydwatkin** [comment]
I believe you fixed this in #22  :)
