### ISSUE TITLE
If item is highlighted <space> should become a valid selector

### ISSUE THREAD

**Issue by lloydwatkin** [lloydwatkin/jquery.autocomplete#6]
If I begin autocomplete and there is a number of results I should be able to cursor key down to one of these items, hit the space bar and have it substitute into my page.

**Comment by michalNetblink** [comment]
Hi!

Well there is a problem when we want to use a space in the search field to match longer phrase than 1 word. 

E.g: `Samsung Galaxy s 20`

When I type `Samsung` and I want to insert the space it's blocked.

It's working fine on https://github.com/devbridge/jQuery-Autocomplete
